# Example
#
# By Nicholas Marriott. Public domain.
#


# For vim-airline
set -g default-terminal "xterm-256color"
set -g default-shell $SHELL


# For vim-gitgutter
set -g focus-events on

# No bells at all
set -g bell-action none

# Lock after 15 minutes
set -g lock-after-time 1800

# Turn on xterm-keys so that additional function keys get escape sequences
set -g xterm-keys on

# Make escape-time less so VIM doesn't suck
set -sg escape-time 0

# Use vi keybindings in copy and choice modes
setw -g mode-keys vi

# Vim-style copy/paste
bind-key -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'V' send -X select-line
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# reload tmux config
unbind r
bind r \
    source-file ~/.tmux.conf \;\
    display 'Reloaded tmux config. :-)'

# set first window to index 1 (not 0) to map more to the keyboard layout...
set -g base-index 1
setw -g pane-base-index 1

# Change the prefix key to C-a
set -g prefix C-Space
unbind C-b
bind C-Space switch-client -l

# Keep your finger on ctrl, or don't
bind-key ^D detach-client
bind-key ^C new-window

# Turn the mouse on
set -g mouse on

# split panes using | and -
bind | split-window -h
bind v split-window -v
unbind '"'
unbind %
set -g display-panes-time 2000

# Keys to toggle monitoring activity in a window, and synchronize-panes
#bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# don't rename windows automatically
set-option -g allow-rename off

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes like vim
bind H resize-pane -L 10
bind L resize-pane -R 10
bind J resize-pane -D 10
bind K resize-pane -U 10

# session switching
unbind (
unbind )
bind N switch-client -n
bind P switch-client -p
bind m command-prompt -p session "switch-client -t '%%'"

# kill panes and windows no confirm
bind x kill-pane
bind X kill-window


# 12 hour clock
set-window-option -g clock-mode-style 12

# resurrect plugin
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# for vim
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
